### ISSUE TITLE
Error when trying to #read_all_streams

### ISSUE THREAD

**Issue by hodak** [arkency/rails_event_store#20]
Hey, after update to `0.2.0` the `es_client.read_all_streams` fails for me (it worked on `0.1.4`).

```ruby
class OrderPlaced < RailsEventStore::Event; end

it "fails RailsEventStore" do
  es_client = RailsEventStore::Client.new
  expect(es_client.read_all_streams).to eql({}) # => true
  order_id = SecureRandom.uuid
  stream_name = "order_#{order_id}"
  event_data = {
    data: {
      id: order_id,
      hodor: "HODOR",
    },
    event_id: SecureRandom.uuid,
  }
  event = OrderPlaced.new(event_data)
  es_client.publish_event(event, stream_name)
  es_client.read_all_streams
end
```

Last line raises:

```
NoMethodError: undefined method `stream' for #<RailsEventStore::Event:0x007fbd22885518>
from /Users/hodak/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/ruby_event_store-0.2.0/lib/ruby_event_store/actions/read_all_streams.rb:10:in `block in call'
```

Which points to this line in [ruby_event_store](https://github.com/arkency/ruby_event_store/): https://github.com/arkency/ruby_event_store/blob/2cab39a85a8431dd682a0c71008d32b87d66ee4d/lib/ruby_event_store/actions/read_all_streams.rb#L10

Which makes sense, because when I read repository manually, it doesn't seem to have `stream` attribute:

```
[4] pry(#<RSpec::ExampleGroups::ApiOrdersController::ValidParams>)> RailsEventStore::Repositories::EventRepository.new.get_all_events
=> [#<RailsEventStore::Event:0x007fbd223257d0
  @data={:id=>"cf5ecc88-e7b7-46b9-88f3-1eb2e2fd1c8d", :hodor=>"HODOR"},
  @event_id="2e8f45ea-b1c3-48c5-be1e-2226ec5f84a0",
  @event_type="OrderPlaced",
  @metadata={:published_at=>2016-02-24 17:52:58 UTC}>]
```

**Comment by mpraglowski** [comment]
Nice catch :) Working on a fix and a way to improve tests.

**Comment by mpraglowski** [comment]
Fixed in PR #21 (rails_event_store 0.2.1)
